### ISSUE TITLE
Search for Workspace Cards doesn't work when multiple roots in workspace

### ISSUE THREAD

**Issue by alevinetx** [MadeWithCards/AdaptiveCardsStudio#1]
When searching for `**/*.json` to find cards in a workspace, the search only looks at `vscode.workspace.rootPath`, which is also deprecated, instead of iterating through `vscode.workspace.workspaceFolders`.

see:  https://code.visualstudio.com/api/references/vscode-api#workspace.workspaceFolders

**Comment by DeeJayTC** [comment]
Nice find, thanks! Gonna update that over the weekend.

**Comment by alevinetx** [comment]
May I suggest that they're grouped in the nav panel by their respective folder, maybe in collapsible/accordion containers?  I think that would go a long way with the usability when working with multiple projects.  Maybe you have a better idea :)

**Comment by alevinetx** [comment]
Also, would be happy to test!

**Comment by DeeJayTC** [comment]
Sure! Ill let you know when its done..didnt have the time yet. This week for sure.
