### ISSUE TITLE
[ENHANCEMENT]: Improvements to Workspace Cards list

### ISSUE THREAD

**Issue by garrytrinder** [MadeWithCards/AdaptiveCardsStudio#12]
Cards are displayed in the Workspace Cards view irrespective of where they are in the folder structure, however when using Adaptive Cards in a project, it is common for JSON for files to be copied to other folders as part of a build process .e.g. `/dist`.

This results in multiple versions of the cards being displayed in the list with the same name, this makes is difficult to know whether you are updating the source card or the copy.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/11563347/184361340-e1318e2e-199f-4328-a29c-7bd04e6c5bab.png">

It would help if we could exclude certain folders from the workspace cards list, or alternatively give some indication on the item in the list which folder it is stored in.

**Comment by DeeJayTC** [comment]
Hey,
the next version will have a configuration open where you can add a comma seperated list of folders it should ignore. 

Thanks, nice suggestion!!

**Comment by DeeJayTC** [comment]
Ignorable  folders is added in 1.2.0
