### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by PowerDBAKlaas** [MadeWithCards/AdaptiveCardsStudio#14]
- Issue Type: `Performance`
- Extension Name: `adaptivecardsstudiobeta`
- Extension Version: `1.1.9`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/KE967~1.VAN/AppData/Local/Temp/madewithcardsio.adaptivecardsstudiobeta-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DeeJayTC** [comment]
Hey @PowerDBAKlaas , can you make sure to actually attach the file? 

Alternatively send it to tim@madewithcards.io 

Thaanks :)
